In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df =pd.read_csv(r"/00 Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
X =df[['Age','EstimatedSalary']]
Y = df['Purchased']

In [ ]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
#Train Test Split
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [ ]:
X_train

     Age  EstimatedSalary
93    29            28000
23    45            22000
299   46           117000
13    32            18000
90    22            81000
..   ...              ...
255   52            90000
72    20            23000
396   51            23000
235   46            79000
37    30            49000

[320 rows x 2 columns]

In [ ]:
Y_train

93     0
23     1
299    1
13     0
90     0
      ..
255    1
72     0
396    1
235    1
37     0
Name: Purchased, Length: 320, dtype: int64

In [ ]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
X_test

     Age  EstimatedSalary
398   36            33000
125   39            61000
328   36           118000
339   39           122000
172   26           118000
..   ...              ...
347   54           108000
41    33            51000
180   26            16000
132   30            87000
224   35            60000

[80 rows x 2 columns]

In [ ]:
Y_test

398    0
125    0
328    1
339    1
172    0
      ..
347    1
41     0
180    0
132    0
224    0
Name: Purchased, Length: 80, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler().set_output(transform="pandas")

In [ ]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

In [ ]:
X_train_scaled

          Age  EstimatedSalary
93  -0.803301        -1.191218
23   0.756980        -1.368598
299  0.854498         1.439920
13  -0.510748        -1.486851
90  -1.485924         0.375639
..        ...              ...
255  1.439603         0.641709
72  -1.680959        -1.339035
396  1.342085        -1.339035
235  0.854498         0.316513
37  -0.705783        -0.570388

[320 rows x 2 columns]

In [ ]:
X_test_scaled

          Age  EstimatedSalary
398 -0.120678        -1.043401
125  0.171875        -0.215628
328 -0.120678         1.469483
339  0.171875         1.587736
172 -1.095853         1.469483
..        ...              ...
347  1.634638         1.173849
41  -0.413231        -0.511261
180 -1.095853        -1.545978
132 -0.705783         0.553019
224 -0.218196        -0.245191

[80 rows x 2 columns]

In [ ]:
X_train_scaled.shape

(320, 2)

In [ ]:
X_test_scaled.shape

(80, 2)

In [ ]:
X_test.describe()

             Age  EstimatedSalary
count  80.000000        80.000000
mean   39.325000     75537.500000
std    11.204401     34564.906382
min    18.000000     15000.000000
25%    31.000000     50000.000000
50%    38.500000     74000.000000
75%    48.000000     99500.000000
max    60.000000    144000.000000

In [ ]:
X_train.describe()

              Age  EstimatedSalary
count  320.000000       320.000000
mean    37.237500     68293.750000
std     10.270625     33878.650655
min     18.000000     15000.000000
25%     29.000000     43000.000000
50%     37.000000     65000.000000
75%     45.000000     85250.000000
max     60.000000    150000.000000

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr=LogisticRegression()
lr_scaled=LogisticRegression()

In [ ]:
lr.fit(X_train,Y_train)
lr_scaled.fit(X_train_scaled,Y_train)

LogisticRegression()

In [ ]:
y_pred_unscaled =lr.predict(X_test)
y_pred_scaled=lr_scaled.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_unscaled=accuracy_score(Y_test,y_pred_unscaled)
accuracy_scaled=accuracy_score(Y_test,y_pred_scaled)

In [ ]:
print("Accuracy unscaled:",accuracy_unscaled)
print("Accuracy scaled:",accuracy_scaled)

Accuracy unscaled: 0.8375
Accuracy scaled: 0.8375